[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn -c gunicorn.conf.py plant_shop.plant_shop.wsgi:application"
healthcheckPath = "/admin/"
healthcheckTimeout = 300
healthcheckInterval = 30

[deploy.env]
PYTHON_VERSION = "3.9.0"
DJANGO_SETTINGS_MODULE = "plant_shop.plant_shop.settings" 