services:
  - type: web
    name: angels-plant
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install gunicorn
      mkdir -p staticfiles
      python manage.py makemigrations products
      python manage.py makemigrations cart
      python manage.py makemigrations checkout
      python manage.py makemigrations core
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: gunicorn plant_shop.plant_shop.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: RAZORPAY_WEBHOOK_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: angels-plant-db
          property: connectionString

databases:
  - name: angels-plant-db
    databaseName: angels_plant
    user: angels_plant_user
    plan: free 