# Generated by Django 5.2 on 2025-05-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
